server:
  port: 8081

remote:
  management:
    ip: http://127.0.0.1:8080
  wechat:
    url: http://127.0.0.1:8080
    appid: wxc62afc144417346e
    secret: b5a7ea8dcee900d1f1663076ac8dba3b

spring:
  servlet:
    multipart:
      maxFileSize: 10000MB
      maxRequestSize: 10000MB
  #  Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pose-wcmp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  #    MVC搜索路径
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #      模板校验关闭
  thymeleaf:
    check-template-location: false


files:
  upload:
    local:
      path: C:\Users\Administrator\Desktop\files\
      maxFileSize: 104857600

session:
  timeout: 43200000